[
  (dfn_definition)
  (dop1_definition)
  (dop2_definition)
  (namespace)
  (dfn_namespace)
  (dop1_namespace)
  (dop2_namespace)
  (parenthesis)
  (dfn_parenthesis)
  (dop1_parenthesis)
  (dop2_parenthesis)
  (highrank)
  (dfn_highrank)
  (dop1_highrank)
  (dop2_highrank)
] @fold