[
  (definition)
  (names)
  (dfn_names)
  (dop1_names)
  (dop2_names)
  (parenthesis)
  (dfn_parenthesis)
  (dop1_parenthesis)
  (dop2_parenthesis)
  (highrank)
  (dfn_highrank)
  (dop1_highrank)
  (dop2_highrank)
  (trad)
  (block)
  (namespace_script)
  (class_definition)
  (interface_definition)
  (property_section)
] @indent.begin
[
  (elseif)
  (else)
  (case)
  (caselist)
  (end)
  (access_statement)
  (attribute_statement)
  (include_statement)
  (using_statement)
  (field_statement)
] @indent.branch
[
  "}"
  ")"
  "]"
  "∇"
  (endif)
  (endselect)
  (endwith)
  (endsection)
  (endhold)
  (enddisposable)
  (until)
  (endfor)
  (endwhile)
  (endnamespace)
  (endclass)
  (endinterface)
  (endproperty)
  (end)
] @indent.branch @indent.end
(comment) @indent.auto
