/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 22
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_source_file_token1 = 2,
  anon_sym_u22c4 = 3,
  anon_sym_NULL = 4,
  anon_sym_SQUOTE = 5,
  aux_sym_string_literal_token1 = 6,
  anon_sym_SQUOTE2 = 7,
  sym_number_literal = 8,
  sym_primitive = 9,
  sym_comment = 10,
  sym_source_file = 11,
  sym__statement = 12,
  sym_expression_statement = 13,
  aux_sym__expression = 14,
  sym_string_literal = 15,
  aux_sym_source_file_repeat1 = 16,
  aux_sym_source_file_repeat2 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_token1] = "source_file_token1",
  [anon_sym_u22c4] = "\u22c4",
  [anon_sym_NULL] = "\0",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_literal_token1] = "string_literal_content",
  [anon_sym_SQUOTE2] = "'",
  [sym_number_literal] = "number_literal",
  [sym_primitive] = "primitive",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_expression_statement] = "expression_statement",
  [aux_sym__expression] = "_expression",
  [sym_string_literal] = "string_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [anon_sym_u22c4] = anon_sym_u22c4,
  [anon_sym_NULL] = anon_sym_NULL,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_SQUOTE2] = anon_sym_SQUOTE,
  [sym_number_literal] = sym_number_literal,
  [sym_primitive] = sym_primitive,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_expression_statement] = sym_expression_statement,
  [aux_sym__expression] = aux_sym__expression,
  [sym_string_literal] = sym_string_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_u22c4] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NULL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__expression] = {
    .visible = false,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 2,
  [9] = 4,
  [10] = 10,
  [11] = 11,
  [12] = 10,
  [13] = 11,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 20,
  [21] = 19,
};

static const TSCharacterRange sym_primitive_character_set_1[] = {
  {'!', '!'}, {'&', '&'}, {'*', '/'}, {'<', '@'}, {'|', '|'}, {'~', '~'}, {0xa8, 0xa8}, {0xd7, 0xd7},
  {0xf7, 0xf7}, {0x2190, 0x2193}, {0x220a, 0x220a}, {0x2218, 0x2218}, {0x2227, 0x222a}, {0x2260, 0x2262}, {0x2264, 0x2265}, {0x2282, 0x2283},
  {0x2286, 0x2286}, {0x2296, 0x2296}, {0x22a2, 0x22a5}, {0x2308, 0x2308}, {0x230a, 0x230a}, {0x2336, 0x233a}, {0x233d, 0x233d}, {0x233f, 0x2340},
  {0x2349, 0x2349}, {0x234b, 0x234b}, {0x234e, 0x234e}, {0x2352, 0x2352}, {0x2355, 0x2355}, {0x235b, 0x235b}, {0x235e, 0x2360}, {0x2363, 0x2365},
  {0x2368, 0x2368}, {0x236a, 0x236a}, {0x236c, 0x236c}, {0x2371, 0x2374}, {0x2377, 0x2378}, {0x2395, 0x2395}, {0x25cb, 0x25cb},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if ((!eof && lookahead == 00)) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == 0xaf) ADVANCE(8);
      if (lookahead == 0x22c4) ADVANCE(16);
      if (lookahead == 0x235d) ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (set_contains(sym_primitive_character_set_1, 39, lookahead)) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x2206 ||
          lookahead == 0x2359 ||
          (0x24b6 <= lookahead && lookahead <= 0x24cf)) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '\'') ADVANCE(24);
      if (lookahead == 0x235d) ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == 0x235d) ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == 0xaf) ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 5:
      if (lookahead == 0xaf) ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == 0xaf) ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == 0x235d) ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      if ((!eof && lookahead == 00)) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\'') ADVANCE(19);
      if (lookahead == 0xaf) ADVANCE(8);
      if (lookahead == 0x22c4) ADVANCE(16);
      if (lookahead == 0x235d) ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (set_contains(sym_primitive_character_set_1, 39, lookahead)) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x2206 ||
          lookahead == 0x2359 ||
          (0x24b6 <= lookahead && lookahead <= 0x24cf)) ADVANCE(18);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '\'') ADVANCE(19);
      if (lookahead == 0xaf) ADVANCE(8);
      if (lookahead == 0x235d) ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (set_contains(sym_primitive_character_set_1, 39, lookahead)) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x2206 ||
          lookahead == 0x2359 ||
          (0x24b6 <= lookahead && lookahead <= 0x24cf)) ADVANCE(18);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '\n') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_u22c4);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_NULL);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x2206 ||
          lookahead == 0x2359 ||
          (0x24b6 <= lookahead && lookahead <= 0x24cf)) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == 0x235d) ADVANCE(20);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SQUOTE2);
      if (lookahead == '\'') ADVANCE(22);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(4);
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(4);
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_primitive);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 13},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 13},
  [21] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_source_file_token1] = ACTIONS(1),
    [anon_sym_u22c4] = ACTIONS(1),
    [anon_sym_NULL] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE2] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_primitive] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym__statement] = STATE(14),
    [sym_expression_statement] = STATE(14),
    [aux_sym__expression] = STATE(2),
    [sym_string_literal] = STATE(2),
    [aux_sym_source_file_repeat2] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [sym_number_literal] = ACTIONS(7),
    [sym_primitive] = ACTIONS(7),
    [sym_comment] = ACTIONS(11),
  },
  [STATE(2)] = {
    [aux_sym__expression] = STATE(4),
    [sym_string_literal] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [aux_sym_source_file_token1] = ACTIONS(13),
    [anon_sym_u22c4] = ACTIONS(17),
    [anon_sym_NULL] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [sym_number_literal] = ACTIONS(15),
    [sym_primitive] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(15),
    [sym_expression_statement] = STATE(15),
    [aux_sym__expression] = STATE(2),
    [sym_string_literal] = STATE(2),
    [aux_sym_source_file_repeat2] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [sym_number_literal] = ACTIONS(7),
    [sym_primitive] = ACTIONS(7),
    [sym_comment] = ACTIONS(11),
  },
  [STATE(4)] = {
    [aux_sym__expression] = STATE(4),
    [sym_string_literal] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [aux_sym_source_file_token1] = ACTIONS(23),
    [anon_sym_u22c4] = ACTIONS(28),
    [anon_sym_NULL] = ACTIONS(28),
    [anon_sym_SQUOTE] = ACTIONS(30),
    [sym_number_literal] = ACTIONS(25),
    [sym_primitive] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(16),
    [sym_expression_statement] = STATE(16),
    [aux_sym__expression] = STATE(8),
    [sym_string_literal] = STATE(8),
    [aux_sym_source_file_repeat2] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(38),
    [sym_number_literal] = ACTIONS(35),
    [sym_primitive] = ACTIONS(35),
    [sym_comment] = ACTIONS(11),
  },
  [STATE(6)] = {
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(41),
    [aux_sym_source_file_token1] = ACTIONS(43),
    [anon_sym_u22c4] = ACTIONS(45),
    [anon_sym_NULL] = ACTIONS(45),
    [anon_sym_SQUOTE] = ACTIONS(41),
    [sym_number_literal] = ACTIONS(41),
    [sym_primitive] = ACTIONS(41),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_identifier] = ACTIONS(49),
    [aux_sym_source_file_token1] = ACTIONS(51),
    [anon_sym_u22c4] = ACTIONS(54),
    [anon_sym_NULL] = ACTIONS(54),
    [anon_sym_SQUOTE] = ACTIONS(49),
    [sym_number_literal] = ACTIONS(49),
    [sym_primitive] = ACTIONS(49),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [aux_sym__expression] = STATE(9),
    [sym_string_literal] = STATE(9),
    [sym_identifier] = ACTIONS(57),
    [aux_sym_source_file_token1] = ACTIONS(13),
    [anon_sym_u22c4] = ACTIONS(17),
    [anon_sym_NULL] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(59),
    [sym_number_literal] = ACTIONS(57),
    [sym_primitive] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [aux_sym__expression] = STATE(9),
    [sym_string_literal] = STATE(9),
    [sym_identifier] = ACTIONS(61),
    [aux_sym_source_file_token1] = ACTIONS(23),
    [anon_sym_u22c4] = ACTIONS(28),
    [anon_sym_NULL] = ACTIONS(28),
    [anon_sym_SQUOTE] = ACTIONS(64),
    [sym_number_literal] = ACTIONS(61),
    [sym_primitive] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
    ACTIONS(69), 6,
      anon_sym_u22c4,
      anon_sym_NULL,
      sym_identifier,
      anon_sym_SQUOTE,
      sym_number_literal,
      sym_primitive,
  [16] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
    ACTIONS(73), 6,
      anon_sym_u22c4,
      anon_sym_NULL,
      sym_identifier,
      anon_sym_SQUOTE,
      sym_number_literal,
      sym_primitive,
  [32] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      aux_sym_source_file_token1,
    ACTIONS(69), 6,
      anon_sym_u22c4,
      anon_sym_NULL,
      sym_identifier,
      anon_sym_SQUOTE,
      sym_number_literal,
      sym_primitive,
  [47] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      aux_sym_source_file_token1,
    ACTIONS(73), 6,
      anon_sym_u22c4,
      anon_sym_NULL,
      sym_identifier,
      anon_sym_SQUOTE,
      sym_number_literal,
      sym_primitive,
  [62] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      aux_sym_source_file_token1,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(77), 2,
      anon_sym_u22c4,
      anon_sym_NULL,
  [79] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      aux_sym_source_file_token1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(77), 2,
      anon_sym_u22c4,
      anon_sym_NULL,
  [96] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      aux_sym_source_file_token1,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(77), 2,
      anon_sym_u22c4,
      anon_sym_NULL,
  [110] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      aux_sym_string_literal_token1,
    ACTIONS(83), 1,
      anon_sym_SQUOTE2,
  [120] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_string_literal_token1,
    ACTIONS(87), 1,
      anon_sym_SQUOTE2,
  [130] = 2,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_SQUOTE2,
  [137] = 2,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
  [144] = 2,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_SQUOTE2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 16,
  [SMALL_STATE(12)] = 32,
  [SMALL_STATE(13)] = 47,
  [SMALL_STATE(14)] = 62,
  [SMALL_STATE(15)] = 79,
  [SMALL_STATE(16)] = 96,
  [SMALL_STATE(17)] = 110,
  [SMALL_STATE(18)] = 120,
  [SMALL_STATE(19)] = 130,
  [SMALL_STATE(20)] = 137,
  [SMALL_STATE(21)] = 144,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expression, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression, 2, 0, 0), SHIFT_REPEAT(4),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expression, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression, 2, 0, 0), SHIFT_REPEAT(17),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(8),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(18),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression, 2, 0, 0), SHIFT_REPEAT(9),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression, 2, 0, 0), SHIFT_REPEAT(18),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [91] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_apl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "apl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
