/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_SQUOTE = 2,
  aux_sym_string_token1 = 3,
  sym_number = 4,
  sym_primitive = 5,
  anon_sym_u22c4 = 6,
  anon_sym_LF = 7,
  anon_sym_u235d = 8,
  aux_sym_comment_token1 = 9,
  sym_source_file = 10,
  sym__statements = 11,
  sym_statement = 12,
  sym__token = 13,
  sym_string = 14,
  aux_sym__brk = 15,
  sym_comment = 16,
  aux_sym__statements_repeat1 = 17,
  aux_sym_statement_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_fragment",
  [sym_number] = "number",
  [sym_primitive] = "primitive",
  [anon_sym_u22c4] = "\u22c4",
  [anon_sym_LF] = "\n",
  [anon_sym_u235d] = "\u235d",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym__statements] = "_statements",
  [sym_statement] = "statement",
  [sym__token] = "_token",
  [sym_string] = "string",
  [aux_sym__brk] = "_brk",
  [sym_comment] = "comment",
  [aux_sym__statements_repeat1] = "_statements_repeat1",
  [aux_sym_statement_repeat1] = "statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_number] = sym_number,
  [sym_primitive] = sym_primitive,
  [anon_sym_u22c4] = anon_sym_u22c4,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_u235d] = anon_sym_u235d,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym__statements] = sym__statements,
  [sym_statement] = sym_statement,
  [sym__token] = sym__token,
  [sym_string] = sym_string,
  [aux_sym__brk] = aux_sym__brk,
  [sym_comment] = sym_comment,
  [aux_sym__statements_repeat1] = aux_sym__statements_repeat1,
  [aux_sym_statement_repeat1] = aux_sym_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_u22c4] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u235d] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statements] = {
    .visible = false,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__brk] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__statements_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static const TSCharacterRange sym_primitive_character_set_1[] = {
  {'!', '!'}, {'&', '&'}, {'*', '/'}, {'<', '@'}, {'|', '|'}, {'~', '~'}, {0xa8, 0xa8}, {0xd7, 0xd7},
  {0xf7, 0xf7}, {0x2190, 0x2193}, {0x220a, 0x220a}, {0x2218, 0x2218}, {0x2227, 0x222a}, {0x2260, 0x2262}, {0x2264, 0x2265}, {0x2282, 0x2283},
  {0x2286, 0x2286}, {0x2296, 0x2296}, {0x22a2, 0x22a5}, {0x2308, 0x2308}, {0x230a, 0x230a}, {0x2336, 0x233a}, {0x233d, 0x233d}, {0x233f, 0x2340},
  {0x2349, 0x2349}, {0x234b, 0x234b}, {0x234e, 0x234e}, {0x2352, 0x2352}, {0x2355, 0x2355}, {0x235b, 0x235b}, {0x235e, 0x2360}, {0x2363, 0x2365},
  {0x2368, 0x2368}, {0x236a, 0x236a}, {0x236c, 0x236c}, {0x2371, 0x2374}, {0x2377, 0x2378}, {0x2395, 0x2395}, {0x25cb, 0x25cb},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\'') ADVANCE(11);
      if (lookahead == 0xaf) ADVANCE(5);
      if (lookahead == 0x22c4) ADVANCE(21);
      if (lookahead == 0x235d) ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (set_contains(sym_primitive_character_set_1, 39, lookahead)) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x2206 ||
          lookahead == 0x2359 ||
          (0x24b6 <= lookahead && lookahead <= 0x24cf)) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 0xaf) ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 0xaf) ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 0xaf) ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 0x2206 ||
          lookahead == 0x2359 ||
          (0x24b6 <= lookahead && lookahead <= 0x24cf)) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\'') ADVANCE(1);
      if (lookahead == 0x235d) ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\'') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(2);
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(2);
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_primitive);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_u22c4);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_u235d);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_u235d);
      if (lookahead == '\'') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_u235d);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == 0x235d) ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 26},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 0},
  [25] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_primitive] = ACTIONS(1),
    [anon_sym_u22c4] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_u235d] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym__statements] = STATE(20),
    [sym_statement] = STATE(14),
    [sym__token] = STATE(11),
    [sym_string] = STATE(10),
    [aux_sym__brk] = STATE(5),
    [sym_comment] = STATE(1),
    [aux_sym_statement_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [sym_number] = ACTIONS(7),
    [sym_primitive] = ACTIONS(7),
    [anon_sym_u22c4] = ACTIONS(11),
    [anon_sym_LF] = ACTIONS(11),
    [anon_sym_u235d] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_statement] = STATE(19),
    [sym__token] = STATE(11),
    [sym_string] = STATE(10),
    [aux_sym__brk] = STATE(9),
    [sym_comment] = STATE(2),
    [aux_sym_statement_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [sym_number] = ACTIONS(7),
    [sym_primitive] = ACTIONS(7),
    [anon_sym_u22c4] = ACTIONS(11),
    [anon_sym_LF] = ACTIONS(11),
    [anon_sym_u235d] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_statement] = STATE(19),
    [sym__token] = STATE(11),
    [sym_string] = STATE(10),
    [aux_sym__brk] = STATE(9),
    [sym_comment] = STATE(3),
    [aux_sym_statement_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [sym_number] = ACTIONS(7),
    [sym_primitive] = ACTIONS(7),
    [anon_sym_u22c4] = ACTIONS(11),
    [anon_sym_LF] = ACTIONS(11),
    [anon_sym_u235d] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_statement] = STATE(19),
    [sym__token] = STATE(11),
    [sym_string] = STATE(10),
    [aux_sym__brk] = STATE(9),
    [sym_comment] = STATE(4),
    [aux_sym_statement_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [sym_number] = ACTIONS(7),
    [sym_primitive] = ACTIONS(7),
    [anon_sym_u22c4] = ACTIONS(11),
    [anon_sym_LF] = ACTIONS(11),
    [anon_sym_u235d] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_statement] = STATE(16),
    [sym__token] = STATE(11),
    [sym_string] = STATE(10),
    [aux_sym__brk] = STATE(9),
    [sym_comment] = STATE(5),
    [aux_sym_statement_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [sym_number] = ACTIONS(7),
    [sym_primitive] = ACTIONS(7),
    [anon_sym_u22c4] = ACTIONS(11),
    [anon_sym_LF] = ACTIONS(11),
    [anon_sym_u235d] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_statement] = STATE(19),
    [sym__token] = STATE(11),
    [sym_string] = STATE(10),
    [aux_sym__brk] = STATE(9),
    [sym_comment] = STATE(6),
    [aux_sym_statement_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [sym_number] = ACTIONS(7),
    [sym_primitive] = ACTIONS(7),
    [anon_sym_u22c4] = ACTIONS(11),
    [anon_sym_LF] = ACTIONS(11),
    [anon_sym_u235d] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__token] = STATE(11),
    [sym_string] = STATE(10),
    [sym_comment] = STATE(7),
    [aux_sym_statement_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [sym_number] = ACTIONS(7),
    [sym_primitive] = ACTIONS(7),
    [anon_sym_u22c4] = ACTIONS(19),
    [anon_sym_LF] = ACTIONS(19),
    [anon_sym_u235d] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym__token] = STATE(11),
    [sym_string] = STATE(10),
    [sym_comment] = STATE(8),
    [aux_sym_statement_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(26),
    [sym_number] = ACTIONS(23),
    [sym_primitive] = ACTIONS(23),
    [anon_sym_u22c4] = ACTIONS(21),
    [anon_sym_LF] = ACTIONS(21),
    [anon_sym_u235d] = ACTIONS(3),
  },
  [STATE(9)] = {
    [aux_sym__brk] = STATE(9),
    [sym_comment] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [sym_number] = ACTIONS(29),
    [sym_primitive] = ACTIONS(29),
    [anon_sym_u22c4] = ACTIONS(31),
    [anon_sym_LF] = ACTIONS(31),
    [anon_sym_u235d] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      anon_sym_u235d,
    STATE(10), 1,
      sym_comment,
    ACTIONS(34), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_SQUOTE,
      sym_number,
      sym_primitive,
      anon_sym_u22c4,
      anon_sym_LF,
  [16] = 3,
    ACTIONS(3), 1,
      anon_sym_u235d,
    STATE(11), 1,
      sym_comment,
    ACTIONS(36), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_SQUOTE,
      sym_number,
      sym_primitive,
      anon_sym_u22c4,
      anon_sym_LF,
  [32] = 3,
    ACTIONS(3), 1,
      anon_sym_u235d,
    STATE(12), 1,
      sym_comment,
    ACTIONS(38), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_SQUOTE,
      sym_number,
      sym_primitive,
      anon_sym_u22c4,
      anon_sym_LF,
  [48] = 3,
    ACTIONS(3), 1,
      anon_sym_u235d,
    STATE(13), 1,
      sym_comment,
    ACTIONS(40), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_SQUOTE,
      sym_number,
      sym_primitive,
      anon_sym_u22c4,
      anon_sym_LF,
  [64] = 6,
    ACTIONS(3), 1,
      anon_sym_u235d,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym__brk,
    STATE(14), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym__statements_repeat1,
    ACTIONS(11), 2,
      anon_sym_u22c4,
      anon_sym_LF,
  [84] = 6,
    ACTIONS(3), 1,
      anon_sym_u235d,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      aux_sym__brk,
    STATE(15), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym__statements_repeat1,
    ACTIONS(11), 2,
      anon_sym_u22c4,
      anon_sym_LF,
  [104] = 6,
    ACTIONS(3), 1,
      anon_sym_u235d,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      aux_sym__brk,
    STATE(16), 1,
      sym_comment,
    STATE(17), 1,
      aux_sym__statements_repeat1,
    ACTIONS(11), 2,
      anon_sym_u22c4,
      anon_sym_LF,
  [124] = 6,
    ACTIONS(3), 1,
      anon_sym_u235d,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym__brk,
    STATE(17), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym__statements_repeat1,
    ACTIONS(11), 2,
      anon_sym_u22c4,
      anon_sym_LF,
  [144] = 5,
    ACTIONS(3), 1,
      anon_sym_u235d,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym__brk,
    ACTIONS(46), 2,
      anon_sym_u22c4,
      anon_sym_LF,
    STATE(18), 2,
      sym_comment,
      aux_sym__statements_repeat1,
  [162] = 3,
    ACTIONS(3), 1,
      anon_sym_u235d,
    STATE(19), 1,
      sym_comment,
    ACTIONS(44), 3,
      ts_builtin_sym_end,
      anon_sym_u22c4,
      anon_sym_LF,
  [174] = 3,
    ACTIONS(3), 1,
      anon_sym_u235d,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_comment,
  [184] = 3,
    ACTIONS(51), 1,
      anon_sym_u235d,
    ACTIONS(53), 1,
      aux_sym_comment_token1,
    STATE(21), 1,
      sym_comment,
  [194] = 3,
    ACTIONS(3), 1,
      anon_sym_u235d,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      sym_comment,
  [204] = 3,
    ACTIONS(51), 1,
      anon_sym_u235d,
    ACTIONS(57), 1,
      aux_sym_string_token1,
    STATE(23), 1,
      sym_comment,
  [214] = 3,
    ACTIONS(3), 1,
      anon_sym_u235d,
    ACTIONS(59), 1,
      anon_sym_SQUOTE,
    STATE(24), 1,
      sym_comment,
  [224] = 1,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 16,
  [SMALL_STATE(12)] = 32,
  [SMALL_STATE(13)] = 48,
  [SMALL_STATE(14)] = 64,
  [SMALL_STATE(15)] = 84,
  [SMALL_STATE(16)] = 104,
  [SMALL_STATE(17)] = 124,
  [SMALL_STATE(18)] = 144,
  [SMALL_STATE(19)] = 162,
  [SMALL_STATE(20)] = 174,
  [SMALL_STATE(21)] = 184,
  [SMALL_STATE(22)] = 194,
  [SMALL_STATE(23)] = 204,
  [SMALL_STATE(24)] = 214,
  [SMALL_STATE(25)] = 224,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 4, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 3, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__brk, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__brk, 2, 0, 0), SHIFT_REPEAT(12),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__brk, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [55] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_apl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "apl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
